/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.daos;


import java.util.List;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;

import quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table;
import quo.vadis.megasys.utils.jooq.sql.tables.pojos.TestGroup2Entity;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestGroup2Record;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestGroup2Dao extends DAOImpl<TestGroup2Record, TestGroup2Entity, Long> {

    /**
     * Create a new TestGroup2Dao without any configuration
     */
    public TestGroup2Dao() {
        super(TestGroup2Table.TEST_GROUP2, TestGroup2Entity.class);
    }

    /**
     * Create a new TestGroup2Dao with an attached configuration
     */
    public TestGroup2Dao(Configuration configuration) {
        super(TestGroup2Table.TEST_GROUP2, TestGroup2Entity.class, configuration);
    }

    @Override
    public Long getId(TestGroup2Entity object) {
        return object.getGroupId();
    }

    /**
     * Fetch records that have <code>group_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<TestGroup2Entity> fetchRangeOfGroupIdTable(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(TestGroup2Table.TEST_GROUP2.GROUP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<TestGroup2Entity> fetchByGroupIdTable(Long... values) {
        return fetch(TestGroup2Table.TEST_GROUP2.GROUP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>group_id = value</code>
     */
    public TestGroup2Entity fetchOneByGroupIdTable(Long value) {
        return fetchOne(TestGroup2Table.TEST_GROUP2.GROUP_ID, value);
    }

    /**
     * Fetch records that have <code>group_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<TestGroup2Entity> fetchRangeOfGroupNameTable(String lowerInclusive, String upperInclusive) {
        return fetchRange(TestGroup2Table.TEST_GROUP2.GROUP_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_name IN (values)</code>
     */
    public List<TestGroup2Entity> fetchByGroupNameTable(String... values) {
        return fetch(TestGroup2Table.TEST_GROUP2.GROUP_NAME, values);
    }

    /**
     * Fetch records that have <code>payload BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<TestGroup2Entity> fetchRangeOfPayloadTable(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(TestGroup2Table.TEST_GROUP2.PAYLOAD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>payload IN (values)</code>
     */
    public List<TestGroup2Entity> fetchByPayloadTable(JSONB... values) {
        return fetch(TestGroup2Table.TEST_GROUP2.PAYLOAD, values);
    }
}
