/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.records;


import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table;
import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestGroup2;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestGroup2Record extends UpdatableRecordImpl<TestGroup2Record> implements Record3<Long, String, JSONB>, ITestGroup2 {

    private static final long serialVersionUID = 930319887;

    /**
     * Setter for <code>test_group2.group_id</code>.
     */
    @Override
    public void setGroupId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_group2.group_id</code>.
     */
    @Override
    public Long getGroupId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test_group2.group_name</code>.
     */
    @Override
    public void setGroupName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_group2.group_name</code>.
     */
    @Override
    public String getGroupName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test_group2.payload</code>.
     */
    @Override
    public void setPayload(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>test_group2.payload</code>.
     */
    @Override
    public JSONB getPayload() {
        return (JSONB) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, JSONB> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, JSONB> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TestGroup2Table.TEST_GROUP2.GROUP_ID;
    }

    @Override
    public Field<String> field2() {
        return TestGroup2Table.TEST_GROUP2.GROUP_NAME;
    }

    @Override
    public Field<JSONB> field3() {
        return TestGroup2Table.TEST_GROUP2.PAYLOAD;
    }

    @Override
    public Long component1() {
        return getGroupId();
    }

    @Override
    public String component2() {
        return getGroupName();
    }

    @Override
    public JSONB component3() {
        return getPayload();
    }

    @Override
    public Long value1() {
        return getGroupId();
    }

    @Override
    public String value2() {
        return getGroupName();
    }

    @Override
    public JSONB value3() {
        return getPayload();
    }

    @Override
    public TestGroup2Record value1(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public TestGroup2Record value2(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public TestGroup2Record value3(JSONB value) {
        setPayload(value);
        return this;
    }

    @Override
    public TestGroup2Record values(Long value1, String value2, JSONB value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITestGroup2 from) {
        setGroupId(from.getGroupId());
        setGroupName(from.getGroupName());
        setPayload(from.getPayload());
    }

    @Override
    public <E extends ITestGroup2> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestGroup2Record
     */
    public TestGroup2Record() {
        super(TestGroup2Table.TEST_GROUP2);
    }

    /**
     * Create a detached, initialised TestGroup2Record
     */
    public TestGroup2Record(Long groupId, String groupName, JSONB payload) {
        super(TestGroup2Table.TEST_GROUP2);

        set(0, groupId);
        set(1, groupName);
        set(2, payload);
    }
}
