/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.records;


import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import quo.vadis.megasys.utils.jooq.sql.tables.TestUserTable;
import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestUserRecord extends UpdatableRecordImpl<TestUserRecord> implements Record3<Long, String, JSONB>, ITestUser {

    private static final long serialVersionUID = -1736134841;

    /**
     * Setter for <code>test_user.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_user.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test_user.user_name</code>.
     */
    @Override
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_user.user_name</code>.
     */
    @Override
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test_user.payload</code>.
     */
    @Override
    public void setPayload(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>test_user.payload</code>.
     */
    @Override
    public JSONB getPayload() {
        return (JSONB) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, JSONB> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, JSONB> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TestUserTable.TEST_USER.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return TestUserTable.TEST_USER.USER_NAME;
    }

    @Override
    public Field<JSONB> field3() {
        return TestUserTable.TEST_USER.PAYLOAD;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public JSONB component3() {
        return getPayload();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public JSONB value3() {
        return getPayload();
    }

    @Override
    public TestUserRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public TestUserRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public TestUserRecord value3(JSONB value) {
        setPayload(value);
        return this;
    }

    @Override
    public TestUserRecord values(Long value1, String value2, JSONB value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITestUser from) {
        setUserId(from.getUserId());
        setUserName(from.getUserName());
        setPayload(from.getPayload());
    }

    @Override
    public <E extends ITestUser> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestUserRecord
     */
    public TestUserRecord() {
        super(TestUserTable.TEST_USER);
    }

    /**
     * Create a detached, initialised TestUserRecord
     */
    public TestUserRecord(Long userId, String userName, JSONB payload) {
        super(TestUserTable.TEST_USER);

        set(0, userId);
        set(1, userName);
        set(2, payload);
    }
}
