/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import quo.vadis.megasys.utils.jooq.sql.tables.TestUserGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUserGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestUserGroupRecord extends UpdatableRecordImpl<TestUserGroupRecord> implements Record3<Long, Long, String>, ITestUserGroup {

    private static final long serialVersionUID = -1773469635;

    /**
     * Setter for <code>test_user_group.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_user_group.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test_user_group.group_id</code>.
     */
    @Override
    public void setGroupId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_user_group.group_id</code>.
     */
    @Override
    public Long getGroupId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>test_user_group.memo</code>.
     */
    @Override
    public void setMemo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test_user_group.memo</code>.
     */
    @Override
    public String getMemo() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TestUserGroupTable.TEST_USER_GROUP.USER_ID;
    }

    @Override
    public Field<Long> field2() {
        return TestUserGroupTable.TEST_USER_GROUP.GROUP_ID;
    }

    @Override
    public Field<String> field3() {
        return TestUserGroupTable.TEST_USER_GROUP.MEMO;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public Long component2() {
        return getGroupId();
    }

    @Override
    public String component3() {
        return getMemo();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public Long value2() {
        return getGroupId();
    }

    @Override
    public String value3() {
        return getMemo();
    }

    @Override
    public TestUserGroupRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public TestUserGroupRecord value2(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public TestUserGroupRecord value3(String value) {
        setMemo(value);
        return this;
    }

    @Override
    public TestUserGroupRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITestUserGroup from) {
        setUserId(from.getUserId());
        setGroupId(from.getGroupId());
        setMemo(from.getMemo());
    }

    @Override
    public <E extends ITestUserGroup> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestUserGroupRecord
     */
    public TestUserGroupRecord() {
        super(TestUserGroupTable.TEST_USER_GROUP);
    }

    /**
     * Create a detached, initialised TestUserGroupRecord
     */
    public TestUserGroupRecord(Long userId, Long groupId, String memo) {
        super(TestUserGroupTable.TEST_USER_GROUP);

        set(0, userId);
        set(1, groupId);
        set(2, memo);
    }
}
