/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.records;


import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import quo.vadis.megasys.utils.jooq.sql.tables.UserToUsersTable;
import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.IUserToUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToUsersRecord extends TableRecordImpl<UserToUsersRecord> implements Record6<Long, String, JSONB, Long, String, JSONB>, IUserToUsers {

    private static final long serialVersionUID = 1467016087;

    /**
     * Setter for <code>user_to_users.user_id</code>.
     */
    @Override
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_to_users.user_id</code>.
     */
    @Override
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_to_users.user_name</code>.
     */
    @Override
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_to_users.user_name</code>.
     */
    @Override
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_to_users.user_payload</code>.
     */
    @Override
    public void setUserPayload(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_to_users.user_payload</code>.
     */
    @Override
    public JSONB getUserPayload() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>user_to_users.group_id</code>.
     */
    @Override
    public void setGroupId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_to_users.group_id</code>.
     */
    @Override
    public Long getGroupId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>user_to_users.group_name</code>.
     */
    @Override
    public void setGroupName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_to_users.group_name</code>.
     */
    @Override
    public String getGroupName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_to_users.group_payload</code>.
     */
    @Override
    public void setGroupPayload(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_to_users.group_payload</code>.
     */
    @Override
    public JSONB getGroupPayload() {
        return (JSONB) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, JSONB, Long, String, JSONB> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, JSONB, Long, String, JSONB> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserToUsersTable.USER_TO_USERS.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return UserToUsersTable.USER_TO_USERS.USER_NAME;
    }

    @Override
    public Field<JSONB> field3() {
        return UserToUsersTable.USER_TO_USERS.USER_PAYLOAD;
    }

    @Override
    public Field<Long> field4() {
        return UserToUsersTable.USER_TO_USERS.GROUP_ID;
    }

    @Override
    public Field<String> field5() {
        return UserToUsersTable.USER_TO_USERS.GROUP_NAME;
    }

    @Override
    public Field<JSONB> field6() {
        return UserToUsersTable.USER_TO_USERS.GROUP_PAYLOAD;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getUserName();
    }

    @Override
    public JSONB component3() {
        return getUserPayload();
    }

    @Override
    public Long component4() {
        return getGroupId();
    }

    @Override
    public String component5() {
        return getGroupName();
    }

    @Override
    public JSONB component6() {
        return getGroupPayload();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getUserName();
    }

    @Override
    public JSONB value3() {
        return getUserPayload();
    }

    @Override
    public Long value4() {
        return getGroupId();
    }

    @Override
    public String value5() {
        return getGroupName();
    }

    @Override
    public JSONB value6() {
        return getGroupPayload();
    }

    @Override
    public UserToUsersRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserToUsersRecord value2(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserToUsersRecord value3(JSONB value) {
        setUserPayload(value);
        return this;
    }

    @Override
    public UserToUsersRecord value4(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public UserToUsersRecord value5(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public UserToUsersRecord value6(JSONB value) {
        setGroupPayload(value);
        return this;
    }

    @Override
    public UserToUsersRecord values(Long value1, String value2, JSONB value3, Long value4, String value5, JSONB value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserToUsers from) {
        setUserId(from.getUserId());
        setUserName(from.getUserName());
        setUserPayload(from.getUserPayload());
        setGroupId(from.getGroupId());
        setGroupName(from.getGroupName());
        setGroupPayload(from.getGroupPayload());
    }

    @Override
    public <E extends IUserToUsers> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserToUsersRecord
     */
    public UserToUsersRecord() {
        super(UserToUsersTable.USER_TO_USERS);
    }

    /**
     * Create a detached, initialised UserToUsersRecord
     */
    public UserToUsersRecord(Long userId, String userName, JSONB userPayload, Long groupId, String groupName, JSONB groupPayload) {
        super(UserToUsersTable.USER_TO_USERS);

        set(0, userId);
        set(1, userName);
        set(2, userPayload);
        set(3, groupId);
        set(4, groupName);
        set(5, groupPayload);
    }
}
