/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import quo.vadis.megasys.utils.jooq.sql.DefaultSchema;
import quo.vadis.megasys.utils.jooq.sql.Indexes;
import quo.vadis.megasys.utils.jooq.sql.Keys;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestGroupRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestGroupTable extends TableImpl<TestGroupRecord> {

    private static final long serialVersionUID = 2013021973;

    /**
     * The reference instance of <code>test_group</code>
     */
    public static final TestGroupTable TEST_GROUP = new TestGroupTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestGroupRecord> getRecordType() {
        return TestGroupRecord.class;
    }

    /**
     * The column <code>test_group.group_id</code>.
     */
    public final TableField<TestGroupRecord, Long> GROUP_ID = createField(DSL.name("group_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>test_group.group_name</code>.
     */
    public final TableField<TestGroupRecord, String> GROUP_NAME = createField(DSL.name("group_name"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>test_group.payload</code>.
     */
    public final TableField<TestGroupRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * Create a <code>test_group</code> table reference
     */
    public TestGroupTable() {
        this(DSL.name("test_group"), null);
    }

    /**
     * Create an aliased <code>test_group</code> table reference
     */
    public TestGroupTable(String alias) {
        this(DSL.name(alias), TEST_GROUP);
    }

    /**
     * Create an aliased <code>test_group</code> table reference
     */
    public TestGroupTable(Name alias) {
        this(alias, TEST_GROUP);
    }

    private TestGroupTable(Name alias, Table<TestGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private TestGroupTable(Name alias, Table<TestGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TestGroupTable(Table<O> child, ForeignKey<O, TestGroupRecord> key) {
        super(child, key, TEST_GROUP);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TEST_GROUP_PKEY);
    }

    @Override
    public UniqueKey<TestGroupRecord> getPrimaryKey() {
        return Keys.TEST_GROUP_PKEY;
    }

    @Override
    public List<UniqueKey<TestGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<TestGroupRecord>>asList(Keys.TEST_GROUP_PKEY);
    }

    @Override
    public TestGroupTable as(String alias) {
        return new TestGroupTable(DSL.name(alias), this);
    }

    @Override
    public TestGroupTable as(Name alias) {
        return new TestGroupTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestGroupTable rename(String name) {
        return new TestGroupTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestGroupTable rename(Name name) {
        return new TestGroupTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, JSONB> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
