/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import quo.vadis.megasys.utils.jooq.sql.DefaultSchema;
import quo.vadis.megasys.utils.jooq.sql.Indexes;
import quo.vadis.megasys.utils.jooq.sql.Keys;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestUserRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestUserTable extends TableImpl<TestUserRecord> {

    private static final long serialVersionUID = 1774752339;

    /**
     * The reference instance of <code>test_user</code>
     */
    public static final TestUserTable TEST_USER = new TestUserTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestUserRecord> getRecordType() {
        return TestUserRecord.class;
    }

    /**
     * The column <code>test_user.user_id</code>.
     */
    public final TableField<TestUserRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>test_user.user_name</code>.
     */
    public final TableField<TestUserRecord, String> USER_NAME = createField(DSL.name("user_name"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>test_user.payload</code>.
     */
    public final TableField<TestUserRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * Create a <code>test_user</code> table reference
     */
    public TestUserTable() {
        this(DSL.name("test_user"), null);
    }

    /**
     * Create an aliased <code>test_user</code> table reference
     */
    public TestUserTable(String alias) {
        this(DSL.name(alias), TEST_USER);
    }

    /**
     * Create an aliased <code>test_user</code> table reference
     */
    public TestUserTable(Name alias) {
        this(alias, TEST_USER);
    }

    private TestUserTable(Name alias, Table<TestUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TestUserTable(Name alias, Table<TestUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TestUserTable(Table<O> child, ForeignKey<O, TestUserRecord> key) {
        super(child, key, TEST_USER);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TEST_USER_PKEY);
    }

    @Override
    public UniqueKey<TestUserRecord> getPrimaryKey() {
        return Keys.TEST_USER_PKEY;
    }

    @Override
    public List<UniqueKey<TestUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TestUserRecord>>asList(Keys.TEST_USER_PKEY);
    }

    @Override
    public TestUserTable as(String alias) {
        return new TestUserTable(DSL.name(alias), this);
    }

    @Override
    public TestUserTable as(Name alias) {
        return new TestUserTable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestUserTable rename(String name) {
        return new TestUserTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestUserTable rename(Name name) {
        return new TestUserTable(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, JSONB> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
