/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.interfaces;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITestUserGroup extends Serializable {

    /**
     * Setter for <code>test_user_group.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>test_user_group.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>test_user_group.group_id</code>.
     */
    public void setGroupId(Long value);

    /**
     * Getter for <code>test_user_group.group_id</code>.
     */
    public Long getGroupId();

    /**
     * Setter for <code>test_user_group.memo</code>.
     */
    public void setMemo(String value);

    /**
     * Getter for <code>test_user_group.memo</code>.
     */
    public String getMemo();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITestUserGroup
     */
    public void from(quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUserGroup from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITestUserGroup
     */
    public <E extends quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUserGroup> E into(E into);
}
