/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.interfaces;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITestUser extends Serializable {

    /**
     * Setter for <code>test_user.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>test_user.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>test_user.user_name</code>.
     */
    public void setUserName(String value);

    /**
     * Getter for <code>test_user.user_name</code>.
     */
    public String getUserName();

    /**
     * Setter for <code>test_user.payload</code>.
     */
    public void setPayload(JSONB value);

    /**
     * Getter for <code>test_user.payload</code>.
     */
    public JSONB getPayload();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITestUser
     */
    public void from(quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITestUser
     */
    public <E extends quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUser> E into(E into);
}
