/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.interfaces;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITestGroup2 extends Serializable {

    /**
     * Setter for <code>test_group2.group_id</code>.
     */
    public void setGroupId(Long value);

    /**
     * Getter for <code>test_group2.group_id</code>.
     */
    public Long getGroupId();

    /**
     * Setter for <code>test_group2.group_name</code>.
     */
    public void setGroupName(String value);

    /**
     * Getter for <code>test_group2.group_name</code>.
     */
    public String getGroupName();

    /**
     * Setter for <code>test_group2.payload</code>.
     */
    public void setPayload(JSONB value);

    /**
     * Getter for <code>test_group2.payload</code>.
     */
    public JSONB getPayload();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITestGroup2
     */
    public void from(quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestGroup2 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITestGroup2
     */
    public <E extends quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestGroup2> E into(E into);
}
