/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.interfaces;


import java.io.Serializable;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IUserToUsers extends Serializable {

    /**
     * Setter for <code>user_to_users.user_id</code>.
     */
    public void setUserId(Long value);

    /**
     * Getter for <code>user_to_users.user_id</code>.
     */
    public Long getUserId();

    /**
     * Setter for <code>user_to_users.user_name</code>.
     */
    public void setUserName(String value);

    /**
     * Getter for <code>user_to_users.user_name</code>.
     */
    public String getUserName();

    /**
     * Setter for <code>user_to_users.user_payload</code>.
     */
    public void setUserPayload(JSONB value);

    /**
     * Getter for <code>user_to_users.user_payload</code>.
     */
    public JSONB getUserPayload();

    /**
     * Setter for <code>user_to_users.group_id</code>.
     */
    public void setGroupId(Long value);

    /**
     * Getter for <code>user_to_users.group_id</code>.
     */
    public Long getGroupId();

    /**
     * Setter for <code>user_to_users.group_name</code>.
     */
    public void setGroupName(String value);

    /**
     * Getter for <code>user_to_users.group_name</code>.
     */
    public String getGroupName();

    /**
     * Setter for <code>user_to_users.group_payload</code>.
     */
    public void setGroupPayload(JSONB value);

    /**
     * Getter for <code>user_to_users.group_payload</code>.
     */
    public JSONB getGroupPayload();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUserToUsers
     */
    public void from(quo.vadis.megasys.utils.jooq.sql.tables.interfaces.IUserToUsers from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUserToUsers
     */
    public <E extends quo.vadis.megasys.utils.jooq.sql.tables.interfaces.IUserToUsers> E into(E into);
}
