/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.pojos;


import org.jooq.JSONB;

import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestGroupEntity implements ITestGroup {

    private static final long serialVersionUID = 2086677566;

    private Long   groupId;
    private String groupName;
    private JSONB  payload;

    public TestGroupEntity() {}

    public TestGroupEntity(ITestGroup value) {
        this.groupId = value.getGroupId();
        this.groupName = value.getGroupName();
        this.payload = value.getPayload();
    }

    public TestGroupEntity(
        Long   groupId,
        String groupName,
        JSONB  payload
    ) {
        this.groupId = groupId;
        this.groupName = groupName;
        this.payload = payload;
    }

    @Override
    public Long getGroupId() {
        return this.groupId;
    }

    @Override
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    @Override
    public String getGroupName() {
        return this.groupName;
    }

    @Override
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @Override
    public JSONB getPayload() {
        return this.payload;
    }

    @Override
    public void setPayload(JSONB payload) {
        this.payload = payload;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestGroupEntity (");

        sb.append(groupId);
        sb.append(", ").append(groupName);
        sb.append(", ").append(payload);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITestGroup from) {
        setGroupId(from.getGroupId());
        setGroupName(from.getGroupName());
        setPayload(from.getPayload());
    }

    @Override
    public <E extends ITestGroup> E into(E into) {
        into.from(this);
        return into;
    }
}
