/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.pojos;


import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.ITestUserGroup;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestUserGroupEntity implements ITestUserGroup {

    private static final long serialVersionUID = -1646271203;

    private Long   userId;
    private Long   groupId;
    private String memo;

    public TestUserGroupEntity() {}

    public TestUserGroupEntity(ITestUserGroup value) {
        this.userId = value.getUserId();
        this.groupId = value.getGroupId();
        this.memo = value.getMemo();
    }

    public TestUserGroupEntity(
        Long   userId,
        Long   groupId,
        String memo
    ) {
        this.userId = userId;
        this.groupId = groupId;
        this.memo = memo;
    }

    @Override
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public Long getGroupId() {
        return this.groupId;
    }

    @Override
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    @Override
    public String getMemo() {
        return this.memo;
    }

    @Override
    public void setMemo(String memo) {
        this.memo = memo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestUserGroupEntity (");

        sb.append(userId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(memo);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITestUserGroup from) {
        setUserId(from.getUserId());
        setGroupId(from.getGroupId());
        setMemo(from.getMemo());
    }

    @Override
    public <E extends ITestUserGroup> E into(E into) {
        into.from(this);
        return into;
    }
}
