/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql.tables.pojos;


import org.jooq.JSONB;

import quo.vadis.megasys.utils.jooq.sql.tables.interfaces.IUserToUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserToUsersEntity implements IUserToUsers {

    private static final long serialVersionUID = -1015838014;

    private Long   userId;
    private String userName;
    private JSONB  userPayload;
    private Long   groupId;
    private String groupName;
    private JSONB  groupPayload;

    public UserToUsersEntity() {}

    public UserToUsersEntity(IUserToUsers value) {
        this.userId = value.getUserId();
        this.userName = value.getUserName();
        this.userPayload = value.getUserPayload();
        this.groupId = value.getGroupId();
        this.groupName = value.getGroupName();
        this.groupPayload = value.getGroupPayload();
    }

    public UserToUsersEntity(
        Long   userId,
        String userName,
        JSONB  userPayload,
        Long   groupId,
        String groupName,
        JSONB  groupPayload
    ) {
        this.userId = userId;
        this.userName = userName;
        this.userPayload = userPayload;
        this.groupId = groupId;
        this.groupName = groupName;
        this.groupPayload = groupPayload;
    }

    @Override
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public String getUserName() {
        return this.userName;
    }

    @Override
    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Override
    public JSONB getUserPayload() {
        return this.userPayload;
    }

    @Override
    public void setUserPayload(JSONB userPayload) {
        this.userPayload = userPayload;
    }

    @Override
    public Long getGroupId() {
        return this.groupId;
    }

    @Override
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    @Override
    public String getGroupName() {
        return this.groupName;
    }

    @Override
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    @Override
    public JSONB getGroupPayload() {
        return this.groupPayload;
    }

    @Override
    public void setGroupPayload(JSONB groupPayload) {
        this.groupPayload = groupPayload;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserToUsersEntity (");

        sb.append(userId);
        sb.append(", ").append(userName);
        sb.append(", ").append(userPayload);
        sb.append(", ").append(groupId);
        sb.append(", ").append(groupName);
        sb.append(", ").append(groupPayload);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUserToUsers from) {
        setUserId(from.getUserId());
        setUserName(from.getUserName());
        setUserPayload(from.getUserPayload());
        setGroupId(from.getGroupId());
        setGroupName(from.getGroupName());
        setGroupPayload(from.getGroupPayload());
    }

    @Override
    public <E extends IUserToUsers> E into(E into) {
        into.from(this);
        return into;
    }
}
