/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table;
import quo.vadis.megasys.utils.jooq.sql.tables.TestGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserTable;
import quo.vadis.megasys.utils.jooq.sql.tables.UserToUsersTable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 723675348;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>test_group</code>.
     */
    public final TestGroupTable TEST_GROUP = quo.vadis.megasys.utils.jooq.sql.tables.TestGroupTable.TEST_GROUP;

    /**
     * The table <code>test_group2</code>.
     */
    public final TestGroup2Table TEST_GROUP2 = quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table.TEST_GROUP2;

    /**
     * The table <code>test_user</code>.
     */
    public final TestUserTable TEST_USER = quo.vadis.megasys.utils.jooq.sql.tables.TestUserTable.TEST_USER;

    /**
     * The table <code>test_user_group</code>.
     */
    public final TestUserGroupTable TEST_USER_GROUP = quo.vadis.megasys.utils.jooq.sql.tables.TestUserGroupTable.TEST_USER_GROUP;

    /**
     * The table <code>user_to_users</code>.
     */
    public final UserToUsersTable USER_TO_USERS = quo.vadis.megasys.utils.jooq.sql.tables.UserToUsersTable.USER_TO_USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TestGroupTable.TEST_GROUP,
            TestGroup2Table.TEST_GROUP2,
            TestUserTable.TEST_USER,
            TestUserGroupTable.TEST_USER_GROUP,
            UserToUsersTable.USER_TO_USERS);
    }
}
