/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table;
import quo.vadis.megasys.utils.jooq.sql.tables.TestGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserTable;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TEST_GROUP_PKEY = Indexes0.TEST_GROUP_PKEY;
    public static final Index TEST_GROUP2_PKEY = Indexes0.TEST_GROUP2_PKEY;
    public static final Index TEST_USER_PKEY = Indexes0.TEST_USER_PKEY;
    public static final Index TEST_USER_GROUP_PKEY = Indexes0.TEST_USER_GROUP_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index TEST_GROUP_PKEY = Internal.createIndex("test_group_pkey", TestGroupTable.TEST_GROUP, new OrderField[] { TestGroupTable.TEST_GROUP.GROUP_ID }, true);
        public static Index TEST_GROUP2_PKEY = Internal.createIndex("test_group2_pkey", TestGroup2Table.TEST_GROUP2, new OrderField[] { TestGroup2Table.TEST_GROUP2.GROUP_ID }, true);
        public static Index TEST_USER_PKEY = Internal.createIndex("test_user_pkey", TestUserTable.TEST_USER, new OrderField[] { TestUserTable.TEST_USER.USER_ID }, true);
        public static Index TEST_USER_GROUP_PKEY = Internal.createIndex("test_user_group_pkey", TestUserGroupTable.TEST_USER_GROUP, new OrderField[] { TestUserGroupTable.TEST_USER_GROUP.USER_ID, TestUserGroupTable.TEST_USER_GROUP.GROUP_ID }, true);
    }
}
