/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql;


import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table;
import quo.vadis.megasys.utils.jooq.sql.tables.TestGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserTable;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestGroup2Record;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestGroupRecord;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestUserGroupRecord;
import quo.vadis.megasys.utils.jooq.sql.tables.records.TestUserRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TestGroupRecord> TEST_GROUP_PKEY = UniqueKeys0.TEST_GROUP_PKEY;
    public static final UniqueKey<TestGroup2Record> TEST_GROUP2_PKEY = UniqueKeys0.TEST_GROUP2_PKEY;
    public static final UniqueKey<TestUserRecord> TEST_USER_PKEY = UniqueKeys0.TEST_USER_PKEY;
    public static final UniqueKey<TestUserGroupRecord> TEST_USER_GROUP_PKEY = UniqueKeys0.TEST_USER_GROUP_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TestUserGroupRecord, TestUserRecord> TEST_USER_GROUP__TEST_USER_GROUP_USER_ID_FKEY = ForeignKeys0.TEST_USER_GROUP__TEST_USER_GROUP_USER_ID_FKEY;
    public static final ForeignKey<TestUserGroupRecord, TestGroupRecord> TEST_USER_GROUP__TEST_USER_GROUP_GROUP_ID_FKEY = ForeignKeys0.TEST_USER_GROUP__TEST_USER_GROUP_GROUP_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<TestGroupRecord> TEST_GROUP_PKEY = Internal.createUniqueKey(TestGroupTable.TEST_GROUP, "test_group_pkey", TestGroupTable.TEST_GROUP.GROUP_ID);
        public static final UniqueKey<TestGroup2Record> TEST_GROUP2_PKEY = Internal.createUniqueKey(TestGroup2Table.TEST_GROUP2, "test_group2_pkey", TestGroup2Table.TEST_GROUP2.GROUP_ID);
        public static final UniqueKey<TestUserRecord> TEST_USER_PKEY = Internal.createUniqueKey(TestUserTable.TEST_USER, "test_user_pkey", TestUserTable.TEST_USER.USER_ID);
        public static final UniqueKey<TestUserGroupRecord> TEST_USER_GROUP_PKEY = Internal.createUniqueKey(TestUserGroupTable.TEST_USER_GROUP, "test_user_group_pkey", TestUserGroupTable.TEST_USER_GROUP.USER_ID, TestUserGroupTable.TEST_USER_GROUP.GROUP_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<TestUserGroupRecord, TestUserRecord> TEST_USER_GROUP__TEST_USER_GROUP_USER_ID_FKEY = Internal.createForeignKey(quo.vadis.megasys.utils.jooq.sql.Keys.TEST_USER_PKEY, TestUserGroupTable.TEST_USER_GROUP, "test_user_group__test_user_group_user_id_fkey", TestUserGroupTable.TEST_USER_GROUP.USER_ID);
        public static final ForeignKey<TestUserGroupRecord, TestGroupRecord> TEST_USER_GROUP__TEST_USER_GROUP_GROUP_ID_FKEY = Internal.createForeignKey(quo.vadis.megasys.utils.jooq.sql.Keys.TEST_GROUP_PKEY, TestUserGroupTable.TEST_USER_GROUP, "test_user_group__test_user_group_group_id_fkey", TestUserGroupTable.TEST_USER_GROUP.GROUP_ID);
    }
}
