/*
 * This file is generated by jOOQ.
 */
package quo.vadis.megasys.utils.jooq.sql;


import quo.vadis.megasys.utils.jooq.sql.tables.TestGroup2Table;
import quo.vadis.megasys.utils.jooq.sql.tables.TestGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserGroupTable;
import quo.vadis.megasys.utils.jooq.sql.tables.TestUserTable;
import quo.vadis.megasys.utils.jooq.sql.tables.UserToUsersTable;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_group</code>.
     */
    public static final TestGroupTable TEST_GROUP = TestGroupTable.TEST_GROUP;

    /**
     * The table <code>test_group2</code>.
     */
    public static final TestGroup2Table TEST_GROUP2 = TestGroup2Table.TEST_GROUP2;

    /**
     * The table <code>test_user</code>.
     */
    public static final TestUserTable TEST_USER = TestUserTable.TEST_USER;

    /**
     * The table <code>test_user_group</code>.
     */
    public static final TestUserGroupTable TEST_USER_GROUP = TestUserGroupTable.TEST_USER_GROUP;

    /**
     * The table <code>user_to_users</code>.
     */
    public static final UserToUsersTable USER_TO_USERS = UserToUsersTable.USER_TO_USERS;
}
